SELECT ad.ANIMAL_ID, ad.NAME
FROM (SELECT ins.ANIMAL_ID, ins.NAME, TIMESTAMPDIFF(day, ins.DATETIME, outs.DATETIME  ) as diff
    FROM ANIMAL_INS ins
    LEFT JOIN ANIMAL_OUTS outs ON ins.ANIMAL_ID = outs.ANIMAL_ID
    ORDER BY diff DESC
    LIMIT 2) ad